import re
import csv

insert_regex = re.compile(r'^\s*INSERT\s+INTO\s+(\w+)\s*\((.*)\)\s*VALUES\s*\((.*)\)\s*;?\s*$', re.IGNORECASE | re.DOTALL | re.MULTILINE)
print(insert_regex)

# # Read the entire input file into a string
# with open('input.sql', 'r') as sql_file:
#     input_string = sql_file.read()
#     sql_file.close()

# print(input_string)

input_debug = \
'''
--INSERTs generated by GenerateInsert (Build 6)
--Project page: http://github.com/drumsta/sql-generate-insert
SET NOCOUNT ON
INSERT INTO OldestLoggedHistoricalEntries
([Network],[Provider],[OldestBlock])
VALUES
 (1,41,7075)
'''

print(input_debug)

insert_statements = insert_regex.findall(input_debug)
print(insert_statements)
